name: 'data_pipeline'
version: '1.2.0'
config-version: 2

profile: 'data_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ETL_project:
    data_pipeline:
      staging:
        +materialized: table
        snowflake_warehouse: dbt_wh
      marts:
        +materialized: incremental
        snowflake_warehouse: dbt_wh